---
  development:
    DB_FILENAME: app/infrastructure/database/local/dev.db


  test:
    DB_FILENAME: app/infrastructure/database/local/test.db


  app_test:
    # Infrastructure
    DB_FILENAME: app/infrastructure/database/local/test.db
    # Application
    APP_HOST: http://localhost:9000